name: Build
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: python -m pip install -e .[build]
      - name: Run build script
        working-directory: src/piidigger
        run: |
          pyinstaller --onedir --distpath ../../dist -i ../../piidigger.ico --collect-submodules wakepy piidigger.py
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: dist/piidigger
