name: Build Windows Embedded
on:
  push:
  workflow_dispatch:

env:
  py_version: "3.12.6"
  arch: "amd64"
  
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install and Build
        run: |
          python -m venv .venv
          .venv\Scripts\activate
          pip install -e .[win]
          .\build_windows_embedded.ps1 -arch $arch -pyVersion $py_version -venv .venv
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: piidigger-$arch
          path: dist\piidigger-$arch