name: Release

on:
  release:
    types: [published]

concurrency:
  group: release-${{ github.event.release.tag_name }}
  cancel-in-progress: false

jobs:
  verify:
    uses: ./.github/workflows/_release-verify.yml

  publish-pypi:
    needs: verify
    uses: ./.github/workflows/_release-publish-pypi.yml
    secrets: inherit

  build-standalone:
    needs: verify
    uses: ./.github/workflows/_release-build-standalone.yml
    secrets: inherit

  virustotal-scan:
    needs: build-standalone
    uses: ./.github/workflows/_release-virustotal.yml
    secrets: inherit

  deploy-docs:
    needs: verify
    uses: ./.github/workflows/_release-deploy-docs.yml
    secrets: inherit
